// Location Types Configuration
// This file contains all TypeScript types for the location system

import { INDIAN_STATES } from './india-states';

// State names
export type StateName = (typeof INDIAN_STATES)[number];

// City names for Gujarat (manually defined for each state)
export type CityName = 
  | "Ahmedabad"
  | "Surat"
  | "Gandhinagar"
  | "Vadodara"
  | "Rajkot"
  | "Jamnagar"
  | "Bhavnagar"
  | "Anand"
  | "Kheda"
  | "Mehsana"
  | "Surendranagar"
  | "Dahod"
  | "Alirajpur"
  | "Rajpipla"
  | "Vijapur"
  | "Mahisagar"
  | "Panchmahal"
  | "Narmada"
  | "Tapi"
  | "Valsad"
  | "Dangs"
  | "Navsari"
  | "Bharuch"
  | "Nadiad"
  | "Amreli"
  | "Aravalli"
  | "Banaskantha"
  | "Botad"
  | "Chhota Udaipur"
  | "Dang"
  | "Devbhoomi Dwarka"
  | "Gir Somnath"
  | "Junagadh"
  | "Kutch"
  | "Morbi"
  | "Patan"
  | "Porbandar"
  | "Sabarkantha";

// Area names - must be unique across all cities
export type AreaName = 
  | "Prahlad Nagar"
  | "Naroda"
  | "Satellite"
  | "CTM"
  | "Shivranjani"
  | "Nikol"
  | "Thaltej"
  | "Ghatlodiya"
  | "Bapunagar"
  | "Navrangpura"
  | "Vastrapur"
  | "Sarkhej"
  | "Ambawadi"
  | "Bodakdev"
  | "Memnagar"
  | "Isanpur"
  | "Vesu"
  | "Adajan"
  | "Ramdev Nagar"
  | "Sarthana"
  | "Medha"
  | "Dhumal Nagar"
  | "Rander"
  | "Chowk Bazaar"
  | "Mandvi"
  | "Ghod Dod Road"
  | "Varachha"
  | "Majava"
  | "Kamrej"
  | "Hazira"
  | "Chowpatty"
  | "Maghval"
  | "Chhota Ambli"
  | "Vraval"
  | "Kathodara"
  | "Sector 10"
  | "Sector 11"
  | "Sector 12"
  | "Sector 13"
  | "Sector 14"
  | "Sector 15"
  | "Sector 16"
  | "Sector 17"
  | "Sector 18"
  | "Sector 20"
  | "Kalol"
  | "Motera"
  | "Ahmedabad-Gandhinagar Highway"
  | "GIDC"
  | "Vithalapur"
  | "Ghuma"
  | "Kora"
  | "Jhvade"
  | "Tarsali"
  | "Wadaj"
  | "Chandod"
  | "Nizampura"
  | "Maheshwari"
  | "Fatehpur"
  | "Khanderao"
  | "Gopalapura"
  | "Laxmi Road"
  | "Manjalpur"
  | "Alkapuri"
  | "Karelibaug"
  | "Padra"
  | "Chhani"
  | "Babrola"
  | "Dandia Bazaar"
  | "Sayajigunj"
  | "Sardar Patel Nagar"
  | "Vishwamitri"
  | "Jambusar"
  | "Morvi"
  | "Kalawad Road"
  | "Goraj"
  | "Kotda"
  | "Sardar Nagar"
  | "Juna Rokia"
  | "Makarpura"
  | "Island Road"
  | "Sakhret"
  | "Mamta Nagar"
  | "Bhavni Dehari"
  | "Adalaj"
  | "Danta"
  | "Visavadar"
  | "Jetpur"
  | "Pavijetpur"
  | "Vasan"
  | "Madhav"
  | "Suthpar"
  | "Khambhalia"
  | "Bhanvad"
  | "Dhoraji"
  | "Jama"
  | "Palitana"
  | "Veraaval"
  | "Sindhdha"
  | "Chavda"
  | "Ramodi"
  | "Talala"
  | "Gariyadhar"
  | "Jasdan"
  | "Chotila"
  | "Dhari"
  | "Limbdi"
  | "Wankaner"
  | "Madhada"
  | "Lakhani"
  | "Sihor"
  | "Gogas"
  | "Petlad"
  | "Borsad"
  | "Khambhat"
  | "Maroli"
  | "Daskroi"
  | "Thasra"
  | "Choryasi"
  | "Sojitra"
  | "Dhrangadhra"
  | "Halol"
  | "Dabhoi"
  | "Jhagadia"
  | "Maebara"
  | "Kathlal"
  | "Nizar"
  | "Palanpur"
  | "Unjha"
  | "Visnagar"
  | "Sabarmati"
  | "Khedbrahma"
  | "Becharji"
  | "Satlasana"
  | "Radhanpur"
  | "Kheralu"
  | "Himatnagar"
  | "Idar"
  | "Sasangir"
  | "Wadhwan"
  | "Piploda"
  | "Limkheda"
  | "Jhadol"
  | "Santrampur"
  | "Tonk"
  | "Jhabua"
  | "Moti"
  | "Mangrol"
  | "Hargaon"
  | "Baleshwar"
  | "Gogunda"
  | "Samod"
  | "Bhainsdehi"
  | "Jobat"
  | "Adwaha"
  | "Bhawar"
  | "Kashid"
  | "Kanad"
  | "Khapa"
  | "Sagada"
  | "Malhargarh"
  | "Petlawad"
  | "Ranji"
  | "Sardarpur"
  | "Thandla"
  | "Dang"
  | "Valsad"
  | "Dharampur"
  | "Bansda"
  | "Kadar"
  | "Jawad"
  | "Pardi"
  | "Udhana"
  | "Kaprada"
  | "Amaliyad"
  | "Gholvad"
  | "Dungri"
  | "Chikhli"
  | "Gandevi"
  | "Jalalpore"
  | "Nanital"
  | "Bharuch"
  | "Vapi"
  | "Jalalpur"
  | "Nandod"
  | "Dohad"
  | "Savli"
  | "Nasvadi"
  | "Til Nagar"
  | "Ranpur"
  | "Galol"
  | "Sagbara"
  | "Vyara"
  | "Songadh"
  | "Bardoli"
  | "Ahwa"
  | "Ramnagar"
  | "Bhavnagar"
  | "Kheda"
  | "Nadiad"
  | "Mehsana"
  | "Patan"
  | "Dahod"
  | "Alirajpur"
  | "Navsari"
  | "Odhav"
  | "Vatva"
  | "Vastral"
  | "Ramol"
  | "Amraiwadi"
  | "Rabari Colony"
  | "Soni ni Chali"
  | "Khokhra"
  | "Ghodasar"
  | "Charodi"
  | "Maninagar East"
  | "Khokhra Circle"
  | "Kuber Nagar"
  | "Saijpur Bogha"
  | "Asarwa"
  | "Shahibaug"
  | "Vejalpur"
  | "Jodhpur"
  | "Anandnagar"
  | "Jivraj Park"
  | "Makarba"
  | "Bopal"
  | "South Bopal"
  | "Shela"
  | "Shilaj"
  | "Ambli"
  | "Gota"
  | "Chandlodia"
  | "Ghatlodia"
  | "Naranpura"
  | "Sola"
  | "Science City"
  | "Kalupur"
  | "Dariyapur"
  | "Jamalpur"
  | "Khadia"
  | "Raipur"
  | "Rakhial"
  | "Relief Road"
  | "Manek Chowk"
  | "Lal Darwaja"
  | "Astodia"
  | "Shahpur"
  | "Khamasa"
  | "Gomtipur"
  | "Behrampura"
  | "Danilimda"
  | "Kankaria"
  | "Panchkuva"
  | "Delhi Darwaja"
  | "Chandkheda"
  | "New Chandkheda"
  | "Ranip"
  | "Sughad"
  | "Zundal"
  | "Tragad"
  | "Koba Road"
  | "Chharodi"
  | "Paldi"
  | "Ellisbridge"
  | "Law Garden"
  | "C.G. Road"
  | "University Area"
  | "Ashram Road"
  | "Usmanpura"
  | "Old Wadaj"
  | "Riverfront"
  | "Narol"
  | "Vatva GIDC"
  | "Sanand"
  | "Changodar"
  | "Dholera Road"
  | "Bavla"
  | "Daskroi"
  | "Hanspura"
  | "Nava Naroda"
  | "Odhav Ring Road"
  | "Shyamal"
  | "Gulbai Tekra"
  | "University Road"
  | "Vijay Cross Road"
  | "CG Road"
  | "Iscon Cross Road"
  | "Prahladnagar"
  | "Judges Bungalow Road"
  | "Sindhu Bhavan Road"
  | "SP Ring Road"
  | "Tower Road"
  | "Clock Tower"
  | "Station Road"
  | "Bhautik Chowk"
  | "S.T. Bus Stand"
  | "Liliya Road"
  | "Bhavnagar Road"
  | "Babra Road"
  | "Rajkamal Chowk"
  | "Chittal Road"
  | "Hirak Bagh"
  | "Rameshwar Nagar"
  | "Sardar Nagar"
  | "Keriya Road"
  | "Moti Market"
  | "Old Market"
  | "Panvadi"
  | "Vithal Nagar"
  | "Gopal Nagar"
  | "Jawahar Road"
  | "Sanjay Nagar"
  | "Krishna Nagar"
  | "Shantinagar"
  | "Radhika Park"
  | "Vrundavan Society"
  | "Tulsi Park"
  | "Shivaji Nagar"
  | "Gayatri Nagar"
  | "Adarsh Nagar"
  | "Gokul Nagar"
  | "Sanskar Nagar"
  | "Bhakti Nagar"
  | "Siddhivinayak Society"
  | "Shreeji Society"
  | "Hari Om Nagar"
  | "Nilkanth Society"
  | "Anand Nagar"
  | "Bholenath Nagar"
  | "Parth Society"
  | "Vishwakarma Society"
  | "Chakkargadh Road"
  | "Bhandariya Road"
  | "Amreli Bypass"
  | "Railway Crossing"
  | "Mahuva Road"
  | "Amreli GIDC"
  | "Kalorana Road"
  | "Gavadka Road"
  | "Khijadiya Road"
  | "Chittal Industrial Belt"
  | "Oil Mills Zone"
  | "Cotton Ginning Units"
  | "Warehouse Belt"
  | "Bhandariya"
  | "Babapur"
  | "Ankadiya"
  | "Dholarva"
  | "Devaliya"
  | "Gavadka"
  | "Fattepur"
  | "Chadiya"
  | "Baxipur"
  | "Amarpur"
  | "Collector Office"
  | "Court Area"
  | "Police Headquarter"
  | "Civil Hospital"
  | "Education Hub"
  | "Nagnath Temple"
  | "Sardar Ganj"
  | "Amul Dairy Road"
  | "Anand Main Market"
  | "Vithal Udyognagar"
  | "Lambhvel Road"
  | "Ganesh Colony"
  | "Nanikhodiyar"
  | "Iskcon Temple"
  | "Old Bus Stand"
  | "Railway Station"
  | "Vithalbhai Patel Road"
  | "Vivekanand Wadi"
  | "Shiv Shakti Nagar"
  | "Sahjanand Society"
  | "Kedar Park Society"
  | "Vaikunth Society"
  | "Vallabh Vidyanagar"
  | "Bakrol"
  | "Chikhodra"
  | "Karamsad"
  | "Mogri"
  | "Jitodiya"
  | "Gana Road"
  | "Vidhyanagar GIDC"
  | "Anand Agricultural University"
  | "GCET"
  | "Vithal Udyognagar GIDC"
  | "Amul Dairy Industrial"
  | "Bakrol GIDC"
  | "Karamsad Industrial Belt"
  | "Chikhodra GIDC"
  | "Petlad Road"
  | "Bakrol Extension"
  | "Chikhodra Outskirts"
  | "Karamsad New Residential Belt"
  | "Vallabh Vidyanagar Expansion"
  | "Mogri Outskirts"
  | "Jitodiya Extension"
  | "Lambhvel Road Development"
  | "Anand Bypass"
  | "Vasad"
  | "Umreth"
  | "Anklav"
  | "Modasa"
  | "Bayad"
  | "Bhiloda"
  | "Dhansura"
  | "Malpur"
  | "Meghraj"
  | "Khadoda"
  | "Bhatkota"
  | "Shampur"
  | "Vaghodia"
  | "Dholi"
  | "Lalpur"
  | "Sardoi"
  | "Sathamba"
  | "Bordi"
  | "Pagiya na Muvada"
  | "Vatrak"
  | "Hathipura"
  | "Varad"
  | "Mandal"
  | "Chandrana"
  | "Shamlaji"
  | "Dholvani"
  | "Idar Border"
  | "Maljipura"
  | "Kheroj"
  | "Umbari"
  | "Meshwo River"
  | "Akrund"
  | "Vadagam"
  | "Rajpur"
  | "Simli"
  | "Jaswantpura"
  | "Industrial Quarry Belt"
  | "Kherancha"
  | "Taranpur"
  | "Forest Tribal Belt"
  | "Hill Settlements"
  | "Mazum River Belt"
  | "Botad"
  | "Chhota Udaipur"
  | "Gandhinagar"
  | "Jamnagar"
  | "Junagadh"
  | "Vijapur"
  | "Morbi"
  | "Rajpipla"
  | "Porbandar"
  | "Rajkot"
  | "Surat"
  | "Surendranagar"
  | "Vadodara"
  | "150 Feet Ring Road"
  | "Abdasa"
  | "Adipur"
  | "Agricultural Plateau"
  | "Agricultural River Valley"
  | "Agricultural Villages"
  | "Agricultural Wheat Belt"
  | "Agriculture Plateau Villages"
  | "Airport Road"
  | "Airport Road Corridor"
  | "Ajwa Lake"
  | "Alang Ship Breaking Yard"
  | "Ambaji"
  | "Amirgadh"
  | "Amirgadh Forest"
  | "Amod"
  | "Amod Rural Belt"
  | "Anjar"
  | "Ankleshwar"
  | "Ankleshwar GIDC"
  | "Arabian Sea Coastal Villages"
  | "Arabian Sea Shoreline"
  | "Arambhada"
  | "Aravalli Forest Belt"
  | "Banas River Belt"
  | "Barda Hills Forest"
  | "Barda Hills Forest Belt"
  | "Barwala"
  | "Barwala Town"
  | "Becharaji"
  | "Becharaji Auto Hub"
  | "Bedi Port"
  | "Bet Dwarka"
  | "Bhabhar"
  | "Bhabhar Town"
  | "Bhachau"
  | "Bhadravadi"
  | "Bhanvad Rural Belt"
  | "Bharana"
  | "Bharuch GIDC"
  | "Bharuch Old City"
  | "Bharuch Outskirts"
  | "Bhavnagar-Botad Highway"
  | "Bhil Tribal Belt"
  | "Bholav"
  | "Bhuj"
  | "Bilimora"
  | "Bilkha"
  | "Bodeli"
  | "Bodeli GIDC"
  | "Border Banaskantha Influence"
  | "Border Rajasthan Influence"
  | "Border Security Belt"
  | "Bortalav"
  | "Botad Outskirts"
  | "Ceramic Industrial Zone"
  | "Champaner UNESCO"
  | "Chanasma"
  | "Chandisar"
  | "Chavaj"
  | "Chemical Industrial Cluster"
  | "Chiloda"
  | "Chitra GIDC"
  | "Chitrasani"
  | "Chotila Hill Pilgrimage"
  | "Coastal Belt Villages"
  | "Coastal Fishing Villages"
  | "Coastal Fishing Villages Ghogha-Talaja"
  | "Coastal Limestone Cement"
  | "Coastal Mangrol Fishing Belt"
  | "Coastal Salt Belt"
  | "Coastal Umargam"
  | "Coastal Villages"
  | "Collector Office Ahwa"
  | "Cotton Farming Belt"
  | "Dahej"
  | "Dahej Port Industrial Corridor"
  | "Dahej SEZ"
  | "Dandi Coastal Belt"
  | "Dang Forest Reserve"
  | "Dantiwada Dam"
  | "Dantiwada Irrigation Belt"
  | "Dediapada"
  | "Deesa"
  | "Deesa Canal Irrigation"
  | "Deesa GIDC"
  | "Dehgam"
  | "Dehgam Town"
  | "Deodar"
  | "Desert-Edge Habitation"
  | "Devgadh Baria"
  | "Devgadh Baria Town"
  | "Dhanera"
  | "Dhanera Agricultural Belt"
  | "Dhordo"
  | "Dhrol"
  | "Diamond Industry Hub"
  | "Digvijay Plot"
  | "Digvijaygram"
  | "Dolasa"
  | "Dolvan"
  | "Dry Desert Belt"
  | "Dryland Farming Zones"
  | "Dumas Beach"
  | "Dwarka"
  | "Dwarka Highway Corridor"
  | "Dwarkadhish Temple"
  | "Earthquake Reconstruction Towns"
  | "Eco-Tourism Belt"
  | "Eco-Tourism Forest Villages"
  | "Fatehgunj"
  | "Fatepura"
  | "Fatepura Town"
  | "Fishing Harbour"
  | "Fishing Harbour Veraval"
  | "Fishing Villages Okha-Dwarka"
  | "Forest Fringe Tribal Settlements"
  | "Forest Hilly Belt"
  | "Forest Hilly Region"
  | "Forest Hilly Settlements"
  | "Forest Vansda Region"
  | "GIDC Botad"
  | "GIDC Dahod"
  | "GIFT City"
  | "GNFC Ankleshwar"
  | "GNFC Township"
  | "Gadh"
  | "Gadhada"
  | "Gadhada Town"
  | "Galteshwar"
  | "Gandhidham"
  | "Gandhidham Kandla SEZ"
  | "Garbada"
  | "Garbada Town"
  | "Ghogha"
  | "Ghogha Port"
  | "Ghoghamba"
  | "Gir Forest Buffer"
  | "Gir Gadhada"
  | "Gir Gadhada Forest"
  | "Gir National Park Buffer"
  | "Gira Waterfall"
  | "Gira-Purna River Valleys"
  | "Girmal"
  | "Godhra"
  | "Godhra Road"
  | "Godhra Town"
  | "Golden Bridge"
  | "Gondal"
  | "Gondal Agricultural Belt"
  | "Halol Influence Belt"
  | "Halvad"
  | "Hansot"
  | "Harij"
  | "Harshad Mata Temple"
  | "Hazira Port Industrial Zone"
  | "Highway Corridor Settlements"
  | "Hill Forest Regions"
  | "Hill Tribal Habitation"
  | "Hilly Jasdan Belt"
  | "Hilly Tribal Settlements"
  | "Himmatnagar"
  | "Hiran River Basin"
  | "Idar Hill Region"
  | "Industrial Ceramic Belt"
  | "Industrial Corridor"
  | "Industrial Corridor Bhavnagar-Sihor"
  | "Industrial Corridor Nadiad"
  | "Industrial Corridor Sachin-Hazira"
  | "Industrial Corridor Small Units"
  | "Industrial Halol Belt"
  | "Industrial Navsari Belt"
  | "Infocity Gandhinagar"
  | "Jagana"
  | "Jambughoda"
  | "Jamnagar GIDC"
  | "Jasdan Road"
  | "Jessore Forest"
  | "Jetpur Textile Dyeing Hub"
  | "Jhagadia GIDC"
  | "Jhagadia Industrial Belt"
  | "Jhalod"
  | "Jhalod Town"
  | "Jodiya"
  | "Junagadh GIDC"
  | "Kadana"
  | "Kadana Dam"
  | "Kadi"
  | "Kadipani"
  | "Kalanala"
  | "Kalavad"
  | "Kaliyabid"
  | "Kalo Dungar"
  | "Kalol GIDC"
  | "Kalol Influence Belt"
  | "Kalyanpur"
  | "Kalyanpur Town"
  | "Kamboli"
  | "Kandla Port"
  | "Kankrej"
  | "Kankrej Villages"
  | "Kanodar"
  | "Kanodar Industrial"
  | "Kapadvanj"
  | "Kareli"
  | "Karjan"
  | "Katargam"
  | "Kavi"
  | "Kawant"
  | "Kawant Forest"
  | "Keshlu"
  | "Keshod"
  | "Keshod Airport"
  | "Kevadia"
  | "Khambhalia GIDC"
  | "Khambhalia Road"
  | "Khanpur"
  | "Kheda Town"
  | "Koba"
  | "Koba Circle"
  | "Kodinar"
  | "Kodinar GIDC"
  | "Kosamba"
  | "Kudasan"
  | "Kundal Belt"
  | "Kutch Desert Villages"
  | "Kutiyana"
  | "Lakhani Town"
  | "Lakhapat Coastal Stretch"
  | "Lakhpat"
  | "Lathidad"
  | "Limkheda Town"
  | "Link Road"
  | "Little Rann of Kutch Edge"
  | "Lunawada"
  | "Machhu Dam"
  | "Madhavpur Beach"
  | "Maharashtra Border"
  | "Maharashtra Border Forest"
  | "Mahemdavad"
  | "Mahi River Basin"
  | "Mahi River Belt"
  | "Mahudha"
  | "Mahuva"
  | "Mahuva GIDC"
  | "Makarpura GIDC"
  | "Maktampur"
  | "Maliya"
  | "Manavadar"
  | "Mansa"
  | "Mansa Town"
  | "Marine Coastal Villages"
  | "Marine National Park Coastal Belt"
  | "Matar"
  | "Mehsana GIDC"
  | "Mendarda"
  | "Mendarda Fringe"
  | "Metoda GIDC"
  | "Mithapur"
  | "Modhera Sun Temple"
  | "Mount Abu Road"
  | "Mount Girnar"
  | "Mundra"
  | "Mundra Port"
  | "NH-27 Corridor"
  | "NH-48 Industrial Corridor"
  | "NH-51 Coastal Highway"
  | "Nadiad Urban Belt"
  | "Nakhatrana"
  | "Narayan Sarovar"
  | "Narmada Canal Belt"
  | "Narmada River Valley"
  | "Narmada Riverfront"
  | "Naswadi"
  | "Naswadi Tribal Belt"
  | "Nava Vadaj"
  | "Netrang"
  | "Netrang Tribal Belt"
  | "Nilambaug"
  | "Oil & Gas Industrial Stretch"
  | "Oil & Gas ONGC Zones"
  | "Oil & Gas Offshore"
  | "Oil Mill Units"
  | "Okha"
  | "Okha Influence Coastal Villages"
  | "Okha Port"
  | "Okhamandal Peninsula"
  | "Olpad"
  | "Orsang River Belt"
  | "Palanpur GIDC"
  | "Palanpur Outskirts"
  | "Palej"
  | "Palitana Town"
  | "Paliyad"
  | "Palsana"
  | "Panoli GIDC"
  | "Panwadi"
  | "Pardi Influence Border"
  | "Pavagadh Hill"
  | "Pavi Jetpur"
  | "Pavi Jetpur Town"
  | "Pethapur"
  | "Pethapur Handicraft Zone"
  | "Petlad Influence Belt"
  | "Petrochemical Zone"
  | "Petrochemical Zone Ankleshwar-Dahej"
  | "Pipaliya"
  | "Prabhas Patan"
  | "Prabhas Patan Archaeological"
  | "Prantij"
  | "Purna Wildlife Sanctuary"
  | "Radhanpur Road"
  | "Railway Colony Dahod"
  | "Railway Junction Hub"
  | "Railway Junction Zones"
  | "Ranavav"
  | "Ranavav Industrial Belt"
  | "Randesan"
  | "Ranghola"
  | "Rani Amrapura"
  | "Rani ki Vav"
  | "Ranpur Town"
  | "Rapar"
  | "Rathwa Tribal Villages"
  | "Ravapar"
  | "Ravla"
  | "Raysan"
  | "Relief Colony"
  | "Remote Forest Hamlets"
  | "River Tapi Basin"
  | "Rukmini Devi Temple"
  | "Rural Hinterland Clusters"
  | "Sabarmati River Basin"
  | "Sabarmati River Belt"
  | "Sachin GIDC"
  | "Sajanpar"
  | "Salaya Port"
  | "Salt Desert Belt"
  | "Salt Mining Belt"
  | "Salt Pans Coastal Belt"
  | "Salt Production Belt"
  | "Sami"
  | "Samni"
  | "Sankheda"
  | "Sankheda Wood Craft"
  | "Santalpur"
  | "Santalpur Fringe"
  | "Saputara"
  | "Saputara Forest Edge"
  | "Sarangpur"
  | "Sardar Sarovar Dam"
  | "Sargasan"
  | "Sasan Gir"
  | "Sasan Gir Eco-Tourism"
  | "Sayla"
  | "Secretariat Area"
  | "Sector 1"
  | "Sector 19"
  | "Sector 2"
  | "Sector 21"
  | "Sector 22"
  | "Sector 23"
  | "Sector 24"
  | "Sector 25"
  | "Sector 26"
  | "Sector 27"
  | "Sector 28"
  | "Sector 29"
  | "Sector 3"
  | "Sector 30"
  | "Sector 4"
  | "Sector 5"
  | "Sector 6"
  | "Sector 7"
  | "Sector 8"
  | "Sector 9"
  | "Shapar-Veraval Industrial Belt"
  | "Shatrunjaya Hill"
  | "Sherpura"
  | "Shihor GIDC"
  | "Ship Breaking Industrial Coastline"
  | "Shoolpaneshwar Wildlife Sanctuary"
  | "Shuklatirth"
  | "Sidhpur"
  | "Sidhpur Heritage Town"
  | "Sihor Town"
  | "Sikka"
  | "Sikka GIDC"
  | "Silvassa Border"
  | "Singvad"
  | "Somnath"
  | "Somnath Coastal Belt"
  | "Somnath Temple"
  | "Sosiya Ship Recycling Zone"
  | "Statue of Unity"
  | "Subhashnagar"
  | "Subir"
  | "Sudama Temple"
  | "Sugarcane Agricultural Belt"
  | "Sugarcane Industrial Zone"
  | "Suigam"
  | "Suigam Border Desert"
  | "Surat City"
  | "Sutrapada"
  | "Sutrapada Coastal Belt"
  | "Takhteshwar"
  | "Talaja"
  | "Talaja Coastal Belt"
  | "Talala Gir"
  | "Talala Gir Forest Gateway"
  | "Talepura"
  | "Talod"
  | "Tankara"
  | "Tata Chemicals Mithapur"
  | "Tejgadh"
  | "Textile Market Ring Road"
  | "Tharad"
  | "Tharad Border Villages"
  | "Tilakwada"
  | "Tile Manufacturing Belt"
  | "Tribal Belt"
  | "Tribal Belt Ambaji Hills"
  | "Tribal Belt Villages"
  | "Tribal Bhil Settlements"
  | "Tribal Forest Region"
  | "Tribal Hamlets"
  | "Tribal Kaprada Forest Belt"
  | "Tribal Khedbrahma Belt"
  | "Tribal Plateau Region"
  | "Triveni Sangam"
  | "Uchchhal"
  | "Udhna"
  | "Umargam"
  | "Umrala"
  | "Umrala Rural Belt"
  | "Una"
  | "Una Coastal Industrial Belt"
  | "Unjha Spice Market"
  | "Uparkot"
  | "Upleta"
  | "Urban Expansion SMC Zones"
  | "Vadali"
  | "Vadgam"
  | "Vadgam Town"
  | "Vadnagar"
  | "Vadtal"
  | "Vagra"
  | "Vagra Coastal Belt"
  | "Valia"
  | "Valia Forest Belt"
  | "Vallabhipur"
  | "Valod"
  | "Vansda"
  | "Vanthali"
  | "Vapi GIDC"
  | "Vasadi"
  | "Vaso"
  | "Vav"
  | "Vav Desert Villages"
  | "Vavol"
  | "Veraval"
  | "Veraval Port"
  | "Wadhwan Old City"
  | "Waghai"
  | "Waghai Botanical Garden"
  | "Waghawadi Road"
  | "Waghodia"
  | "Waghodia Industrial Belt"
  | "Wankaner Heritage Town"
  | "Warehouse Trading Hubs"
  | "Western Ghats Forest"
  | "White Rann"
  | "Zadeshwar"
  | "Zalod Forest Belt"
  | "Zoz"
;


// Location tree structure
export interface LocationTree {
  [state: string]: {
    [city: string]: AreaName[];
  };
}

// Selected location state
export interface SelectedLocation {
  state: StateName | null;
  city: CityName | null;
  area: AreaName | null;
}

// Location dropdown state
export interface LocationDropdownState {
  state: StateName | null;
  city: CityName | null;
  area: AreaName | null;
  stateOptions: StateName[];
  cityOptions: CityName[];
  areaOptions: AreaName[];
}

// Search query with location
export interface LocationSearchQuery {
  keyword: string;
  state: StateName;
  city: CityName;
  area: AreaName | null;
}

// Form data with location
export interface LocationFormData {
  keyword: string;
  state: StateName;
  city: CityName;
  area: AreaName | "";
}
