// Location Data Configuration
// This file contains the hierarchical location data: State -> City -> Areas
// You can manually add more cities and areas as needed
// Format: { [StateName]: { [CityName]: [AreaName] } }

import type { StateName, CityName, AreaName } from './location-types';
import { INDIAN_STATES } from './india-states';

// Areas for Ahmedabad
const AHMEDABAD_AREAS: AreaName[] = [
  "Naroda",
  "Odhav",
  "Vatva",
  "Vastral",
  "Ramol",
  "Amraiwadi",
  "Rabari Colony",
  "Soni ni Chali",
  "Bapunagar",
  "Khokhra",
  "Isanpur",
  "Ghodasar",
  "CTM",
  "Charodi",
  "Maninagar East",
  "Khokhra Circle",
  "Kuber Nagar",
  "Saijpur Bogha",
  "Asarwa",
  "Shahibaug",
  "Prahlad Nagar",
  "Satellite",
  "Vejalpur",
  "Jodhpur",
  "Anandnagar",
  "Jivraj Park",
  "Makarba",
  "Bodakdev",
  "Bopal",
  "South Bopal",
  "Shela",
  "Shilaj",
  "Thaltej",
  "Ghuma",
  "Ambli",
  "Gota",
  "Chandlodia",
  "Ghatlodia",
  "Navrangpura",
  "Naranpura",
  "Memnagar",
  "Vastrapur",
  "Sola",
  "Science City",
  "Sarkhej",
  "Kalupur",
  "Dariyapur",
  "Jamalpur",
  "Khadia",
  "Raipur",
  "Rakhial",
  "Relief Road",
  "Manek Chowk",
  "Lal Darwaja",
  "Astodia",
  "Shahpur",
  "Khamasa",
  "Gomtipur",
  "Behrampura",
  "Danilimda",
  "Kankaria",
  "Panchkuva",
  "Delhi Darwaja",
  "Motera",
  "Sabarmati",
  "Chandkheda",
  "New Chandkheda",
  "Ranip",
  "Sughad",
  "Zundal",
  "Tragad",
  "Koba Road",
  "Chharodi",
  "Paldi",
  "Ellisbridge",
  "Ambawadi",
  "Law Garden",
  "C.G. Road",
  "University Area",
  "Ashram Road",
  "Usmanpura",
  "Wadaj",
  "Old Wadaj",
  "Riverfront",
  "Narol",
  "Vatva GIDC",
  "Sanand",
  "Changodar",
  "Dholera Road",
  "Bavla",
  "Daskroi",
  "Hanspura",
  "Nava Naroda",
  "Odhav Ring Road",
  "Shyamal",
  "Gulbai Tekra",
  "University Road",
  "Vijay Cross Road",
  "CG Road",
  "Iscon Cross Road",
  "Prahladnagar",
  "Judges Bungalow Road",
  "Sindhu Bhavan Road",
  "SP Ring Road",
  "Shivranjani",
  "Nikol",
];

// Areas for Alirajpur
const ALIRAJPUR_AREAS: AreaName[] = [
  "Alirajpur",
  "Jobat",
  "Bhainsdehi",
  "Adwaha",
  "Bhawar",
  "Kashid",
  "Kanad",
  "Khapa",
  "Sagada",
  "Malhargarh",
  "Petlawad",
  "Ranji",
  "Sardarpur",
  "Thandla",
];

// Areas for Amreli
const AMRELI_AREAS: AreaName[] = [
  "Tower Road",
  "Clock Tower",
  "Station Road",
  "Bhautik Chowk",
  "S.T. Bus Stand",
  "Liliya Road",
  "Bhavnagar Road",
  "Babra Road",
  "Rajkamal Chowk",
  "Chittal Road",
  "Hirak Bagh",
  "Rameshwar Nagar",
  "Sardar Nagar",
  "Keriya Road",
  "Moti Market",
  "Old Market",
  "Panvadi",
  "Vithal Nagar",
  "Gopal Nagar",
  "Jawahar Road",
  "Sanjay Nagar",
  "Krishna Nagar",
  "Shantinagar",
  "Radhika Park",
  "Vrundavan Society",
  "Tulsi Park",
  "Shivaji Nagar",
  "Gayatri Nagar",
  "Adarsh Nagar",
  "Gokul Nagar",
  "Sanskar Nagar",
  "Bhakti Nagar",
  "Siddhivinayak Society",
  "Shreeji Society",
  "Hari Om Nagar",
  "Nilkanth Society",
  "Anand Nagar",
  "Bholenath Nagar",
  "Parth Society",
  "Vishwakarma Society",
  "Chakkargadh Road",
  "Bhandariya Road",
  "Amreli Bypass",
  "Railway Crossing",
  "Mahuva Road",
  "Amreli GIDC",
  "Kalorana Road",
  "Gavadka Road",
  "Khijadiya Road",
  "Chittal Industrial Belt",
  "Oil Mills Zone",
  "Cotton Ginning Units",
  "Warehouse Belt",
  "Bhandariya",
  "Babapur",
  "Ankadiya",
  "Dholarva",
  "Devaliya",
  "Gavadka",
  "Fattepur",
  "Chadiya",
  "Baxipur",
  "Amarpur",
  "Collector Office",
  "Court Area",
  "Police Headquarter",
  "Civil Hospital",
  "Education Hub",
  "Nagnath Temple",
];

// Areas for Anand
const ANAND_AREAS: AreaName[] = [
  "Station Road",
  "Tower Road",
  "Sardar Ganj",
  "Moti Market",
  "Bhautik Chowk",
  "Rajkamal Chowk",
  "Amul Dairy Road",
  "Anand Main Market",
  "Vithal Udyognagar",
  "Lambhvel Road",
  "Ganesh Colony",
  "Nanikhodiyar",
  "Hari Om Nagar",
  "Iskcon Temple",
  "Old Bus Stand",
  "Railway Station",
  "Panvadi",
  "Vithalbhai Patel Road",
  "Vivekanand Wadi",
  "Shiv Shakti Nagar",
  "Vrundavan Society",
  "Shreeji Society",
  "Siddhivinayak Society",
  "Gokul Nagar",
  "Adarsh Nagar",
  "Krishna Nagar",
  "Gayatri Nagar",
  "Bhakti Nagar",
  "Tulsi Park",
  "Anand Nagar",
  "Sanskar Nagar",
  "Parth Society",
  "Shantinagar",
  "Bholenath Nagar",
  "Radhika Park",
  "Sahjanand Society",
  "Kedar Park Society",
  "Nilkanth Society",
  "Vaikunth Society",
  "Vallabh Vidyanagar",
  "Bakrol",
  "Chikhodra",
  "Karamsad",
  "Mogri",
  "Jitodiya",
  "Gana Road",
  "Vidhyanagar GIDC",
  "University Road",
  "Anand Agricultural University",
  "GCET",
  "Vithal Udyognagar GIDC",
  "Amul Dairy Industrial",
  "Bakrol GIDC",
  "Karamsad Industrial Belt",
  "Chikhodra GIDC",
  "Petlad Road",
  "Bakrol Extension",
  "Chikhodra Outskirts",
  "Karamsad New Residential Belt",
  "Vallabh Vidyanagar Expansion",
  "Mogri Outskirts",
  "Jitodiya Extension",
  "Lambhvel Road Development",
  "Anand Bypass",
  "Vasad",
  "Umreth",
  "Anklav",
];

// Areas for Aravalli
const ARAVALLI_AREAS: AreaName[] = [
  "Modasa",
  "Bayad",
  "Bhiloda",
  "Dhansura",
  "Malpur",
  "Meghraj",
  "Khadoda",
  "Bhatkota",
  "Shampur",
  "Vaghodia",
  "Kalol",
  "Dholi",
  "Lalpur",
  "Sardoi",
  "Sathamba",
  "Bordi",
  "Pagiya na Muvada",
  "Vatrak",
  "Hathipura",
  "Varad",
  "Mandal",
  "Chandrana",
  "Shamlaji",
  "Dholvani",
  "Idar Border",
  "Maljipura",
  "Kheroj",
  "Umbari",
  "Meshwo River",
  "Akrund",
  "Vadagam",
  "Rajpur",
  "Simli",
  "Jaswantpura",
  "Industrial Quarry Belt",
  "Kherancha",
  "Taranpur",
  "Forest Tribal Belt",
  "Hill Settlements",
  "Mazum River Belt",
];

// Areas for Banaskantha
const BANASKANTHA_AREAS: AreaName[] = [
  "Palanpur",
  "Deesa",
  "Dhanera",
  "Tharad",
  "Vav",
  "Danta",
  "Deodar",
  "Vadgam",
  "Bhabhar",
  "Kankrej",
  "Suigam",
  "Lakhani",
  "Amirgadh",
  "Santalpur",
  "Chandisar",
  "Lalpur",
  "Gadh",
  "Talepura",
  "Jagana",
  "Kanodar",
  "Chitrasani",
  "Palanpur GIDC",
  "Ambaji",
  "Mount Abu Road",
  "Deesa GIDC",
  "Tharad Border Villages",
  "Vav Desert Villages",
  "Dhanera Agricultural Belt",
  "Kankrej Villages",
  "Bhabhar Town",
  "Lakhani Town",
  "Vadgam Town",
  "Suigam Border Desert",
  "Radhanpur Road",
  "Santalpur Fringe",
  "Amirgadh Forest",
  "Jessore Forest",
  "Dantiwada Dam",
  "Dantiwada Irrigation Belt",
  "Banas River Belt",
  "Deesa Canal Irrigation",
  "Palanpur Outskirts",
  "Kanodar Industrial",
  "NH-27 Corridor",
  "Dryland Farming Zones",
  "Desert-Edge Habitation",
  "Tribal Belt Ambaji Hills",
  "Border Security Belt",
];

// Areas for Bharuch
const BHARUCH_AREAS: AreaName[] = [
  "Bharuch",
  "Ankleshwar",
  "Jambusar",
  "Amod",
  "Vagra",
  "Hansot",
  "Valia",
  "Jhagadia",
  "Netrang",
  "Zadeshwar",
  "Bholav",
  "Dahej",
  "Dahej SEZ",
  "Ankleshwar GIDC",
  "Panoli GIDC",
  "Jhagadia GIDC",
  "Bharuch GIDC",
  "Narmada Riverfront",
  "Sherpura",
  "Chavaj",
  "Keshlu",
  "Kareli",
  "Maktampur",
  "Kamboli",
  "Palej",
  "Kosamba",
  "Amod Rural Belt",
  "Samni",
  "Kora",
  "Kavi",
  "Vagra Coastal Belt",
  "Dahej Port Industrial Corridor",
  "Petrochemical Zone Ankleshwar-Dahej",
  "Oil & Gas Industrial Stretch",
  "GNFC Ankleshwar",
  "GNFC Township",
  "Valia Forest Belt",
  "Netrang Tribal Belt",
  "Jhagadia Industrial Belt",
  "Shuklatirth",
  "Bharuch Old City",
  "Station Road",
  "Link Road",
  "Bharuch Outskirts",
  "Golden Bridge",
  "NH-48 Industrial Corridor",
  "Chemical Industrial Cluster",
];

// Areas for Bhavnagar
const BHAVNAGAR_AREAS: AreaName[] = [
  "Bhavnagar",
  "Ghogha",
  "Sihor",
  "Talaja",
  "Mahuva",
  "Palitana",
  "Gariyadhar",
  "Umrala",
  "Vallabhipur",
  "Waghawadi Road",
  "Nilambaug",
  "Kalanala",
  "Panwadi",
  "Kaliyabid",
  "Sardar Nagar",
  "Airport Road",
  "Subhashnagar",
  "Takhteshwar",
  "Bortalav",
  "Chitra GIDC",
  "Shihor GIDC",
  "Mahuva GIDC",
  "Talaja Coastal Belt",
  "Ghogha Port",
  "Alang Ship Breaking Yard",
  "Sosiya Ship Recycling Zone",
  "Shatrunjaya Hill",
  "Sihor Town",
  "Palitana Town",
  "Umrala Rural Belt",
  "Coastal Fishing Villages Ghogha-Talaja",
  "Industrial Corridor Bhavnagar-Sihor",
  "Salt Production Belt",
  "Ship Breaking Industrial Coastline",
];

// Areas for Botad
const BOTAD_AREAS: AreaName[] = [
  "Botad",
  "Gadhada",
  "Barwala",
  "Ranpur",
  "Station Road",
  "Bhavnagar Road",
  "GIDC Botad",
  "Jasdan Road",
  "Ranghola",
  "Paliyad",
  "Sarangpur",
  "Botad Outskirts",
  "Agricultural Villages",
  "Gadhada Town",
  "Barwala Town",
  "Ranpur Town",
  "Bhavnagar-Botad Highway",
  "Cotton Farming Belt",
  "Oil Mill Units",
  "Warehouse Trading Hubs",
  "Kundal Belt",
  "Lathidad",
  "Bhadravadi",
  "Pipaliya",
  "Rural Hinterland Clusters",
];

// Areas for Chhota Udaipur
const CHHOTA_UIDAPUR_AREAS: AreaName[] = [
  "Chhota Udaipur",
  "Bodeli",
  "Kawant",
  "Naswadi",
  "Sankheda",
  "Pavi Jetpur",
  "Bodeli GIDC",
  "Sankheda Wood Craft",
  "Naswadi Tribal Belt",
  "Kawant Forest",
  "Pavi Jetpur Town",
  "Rathwa Tribal Villages",
  "Bhil Tribal Belt",
  "Orsang River Belt",
  "Vasadi",
  "Zoz",
  "Kadipani",
  "Tejgadh",
  "Rani Amrapura",
  "Forest Hilly Settlements",
  "Tribal Hamlets",
  "Agricultural River Valley",
];

// Areas for Dahod
const DAHOD_AREAS: AreaName[] = [
  "Dahod",
  "Limkheda",
  "Jhalod",
  "Garbada",
  "Devgadh Baria",
  "Fatepura",
  "Station Road",
  "Godhra Road",
  "GIDC Dahod",
  "Limkheda Town",
  "Jhalod Town",
  "Fatepura Town",
  "Devgadh Baria Town",
  "Garbada Town",
  "Tribal Belt Villages",
  "Hill Forest Regions",
  "Mahi River Belt",
  "Singvad",
  "Zalod Forest Belt",
  "Railway Colony Dahod",
  "Industrial Corridor Small Units",
  "Agriculture Plateau Villages",
  "Tribal Plateau Region",
];

// Areas for Dang
const DANG_AREAS: AreaName[] = [
  "Ahwa",
  "Waghai",
  "Subir",
  "Saputara",
  "Girmal",
  "Dang Forest Reserve",
  "Western Ghats Forest",
  "Tribal Bhil Settlements",
  "Gira Waterfall",
  "Purna Wildlife Sanctuary",
  "Collector Office Ahwa",
  "Waghai Botanical Garden",
  "Eco-Tourism Forest Villages",
  "Gira-Purna River Valleys",
  "Remote Forest Hamlets",
  "Maharashtra Border Forest",
  "Hill Tribal Habitation",
];

// Areas for Devbhoomi Dwarka
const DEVBHOOMI_DWARKA_AREAS: AreaName[] = [
  "Dwarka",
  "Kalyanpur",
  "Bhanvad",
  "Khambhalia",
  "Okha",
  "Ravla",
  "Dwarkadhish Temple",
  "Rukmini Devi Temple",
  "Bet Dwarka",
  "Okha Port",
  "Salaya Port",
  "Khambhalia GIDC",
  "Bhanvad Rural Belt",
  "Kalyanpur Town",
  "Marine Coastal Villages",
  "Fishing Villages Okha-Dwarka",
  "Harshad Mata Temple",
  "Arambhada",
  "Bharana",
  "Mithapur",
  "Tata Chemicals Mithapur",
  "Salt Pans Coastal Belt",
  "Oil & Gas Offshore",
  "NH-51 Coastal Highway",
  "Arabian Sea Coastal Villages",
  "Okhamandal Peninsula",
  "Lakhapat Coastal Stretch",
];

// Areas for Gandhinagar
const GANDHINAGAR_AREAS: AreaName[] = [
  "Gandhinagar",
  "Kalol",
  "Mansa",
  "Dehgam",
  "Sector 1",
  "Sector 2",
  "Sector 3",
  "Sector 4",
  "Sector 5",
  "Sector 6",
  "Sector 7",
  "Sector 8",
  "Sector 9",
  "Sector 10",
  "Sector 11",
  "Sector 12",
  "Sector 13",
  "Sector 14",
  "Sector 15",
  "Sector 16",
  "Sector 17",
  "Sector 18",
  "Sector 19",
  "Sector 20",
  "Sector 21",
  "Sector 22",
  "Sector 23",
  "Sector 24",
  "Sector 25",
  "Sector 26",
  "Sector 27",
  "Sector 28",
  "Sector 29",
  "Sector 30",
  "Infocity Gandhinagar",
  "GIFT City",
  "Randesan",
  "Raysan",
  "Koba",
  "Adalaj",
  "Zundal",
  "Kudasan",
  "Sargasan",
  "Pethapur",
  "Chiloda",
  "Motera",
  "Koba Circle",
  "Airport Road Corridor",
  "Kalol GIDC",
  "Mansa Town",
  "Dehgam Town",
  "Pethapur Handicraft Zone",
  "Secretariat Area",
  "Vavol",
  "Nava Vadaj",
  "Highway Corridor Settlements",
  "Sabarmati River Belt",
];

// Areas for Gir Somnath
const GIR_SOMNATH_AREAS: AreaName[] = [
  "Veraval",
  "Somnath",
  "Prabhas Patan",
  "Una",
  "Kodinar",
  "Talala",
  "Sutrapada",
  "Gir Gadhada",
  "Somnath Temple",
  "Triveni Sangam",
  "Veraval Port",
  "Fishing Harbour Veraval",
  "Prabhas Patan Archaeological",
  "Somnath Coastal Belt",
  "Una Coastal Industrial Belt",
  "Kodinar GIDC",
  "Talala Gir Forest Gateway",
  "Gir National Park Buffer",
  "Sutrapada Coastal Belt",
  "Gir Gadhada Forest",
  "Coastal Fishing Villages",
  "Hiran River Basin",
  "Mendarda Fringe",
  "Sasan Gir Eco-Tourism",
  "Coastal Limestone Cement",
  "Arabian Sea Shoreline",
  "Forest Fringe Tribal Settlements",
];

// Areas for Jamnagar
const JAMNAGAR_AREAS: AreaName[] = [
  "Jamnagar",
  "Khambhalia",
  "Jodiya",
  "Digvijaygram",
  "Digvijay Plot",
  "Bedi Port",
  "Sikka",
  "Sikka GIDC",
  "Khambhalia Road",
  "Dwarka Highway Corridor",
  "Kalavad",
  "Lalpur",
  "Dhrol",
  "Jamnagar GIDC",
  "Relief Colony",
  "Marine National Park Coastal Belt",
  "Okha Influence Coastal Villages",
  "Barda Hills Forest Belt",
];

// Areas for Junagadh
const JUNAGADH_AREAS: AreaName[] = [
  "Junagadh",
  "Manavadar",
  "Mendarda",
  "Keshod",
  "Mangrol",
  "Visavadar",
  "Talala Gir",
  "Sasan Gir",
  "Gir Forest Buffer",
  "Mount Girnar",
  "Uparkot",
  "Dolasa",
  "Vanthali",
  "Bilkha",
  "Junagadh GIDC",
  "Keshod Airport",
  "Coastal Mangrol Fishing Belt",
];

// Areas for Kheda
const KHEDA_AREAS: AreaName[] = [
  "Nadiad",
  "Kapadvanj",
  "Mahemdavad",
  "Matar",
  "Thasra",
  "Mahudha",
  "Kheda Town",
  "Nadiad Urban Belt",
  "Petlad Influence Belt",
  "Vaso",
  "Kathlal",
  "Galteshwar",
  "Vadtal",
  "Narmada Canal Belt",
  "Industrial Corridor Nadiad",
  "Petlad Road",
];

// Areas for Kutch
const KUTCH_AREAS: AreaName[] = [
  "Bhuj",
  "Anjar",
  "Gandhidham",
  "Mandvi",
  "Mundra",
  "Bhachau",
  "Rapar",
  "Nakhatrana",
  "Abdasa",
  "Lakhpat",
  "Kandla Port",
  "Mundra Port",
  "Adipur",
  "Gandhidham Kandla SEZ",
  "White Rann",
  "Dhordo",
  "Kalo Dungar",
  "Narayan Sarovar",
  "Kutch Desert Villages",
  "Coastal Salt Belt",
  "Earthquake Reconstruction Towns",
];

// Areas for Mahisagar
const MAHISAGAR_AREAS: AreaName[] = [
  "Lunawada",
  "Santrampur",
  "Kadana",
  "Khanpur",
  "Kadana Dam",
  "Tribal Belt",
  "Forest Hilly Belt",
  "Mahi River Basin",
  "Border Rajasthan Influence",
  "Agricultural Plateau",
];

// Areas for Mehsana
const MEHSANA_AREAS: AreaName[] = [
  "Mehsana",
  "Visnagar",
  "Unjha",
  "Kadi",
  "Kheralu",
  "Becharaji",
  "Satlasana",
  "Vadnagar",
  "Vijapur",
  "Mehsana GIDC",
  "Becharaji Auto Hub",
  "Unjha Spice Market",
  "Kalol Influence Belt",
  "Railway Junction Zones",
  "Agricultural Wheat Belt",
  "Oil & Gas ONGC Zones",
];

// Areas for Morbi
const MORBI_AREAS: AreaName[] = [
  "Morbi",
  "Wankaner",
  "Tankara",
  "Halvad",
  "Maliya",
  "Ceramic Industrial Zone",
  "Tile Manufacturing Belt",
  "Ravapar",
  "Sajanpar",
  "Wankaner Heritage Town",
  "Salt Mining Belt",
  "Machhu Dam",
  "Industrial Corridor",
];

// Areas for Nadiad
const NADIAD_AREAS: AreaName[] = [
  "Nadiad",
  "Kapadvanj",
  "Mahemdavad",
  "Matar",
  "Thasra",
  "Mahudha",
  "Kheda Town",
  "Vaso",
  "Kathlal",
  "Galteshwar",
  "Vadtal",
  "Petlad Road",
  "Narmada Canal Belt",
];

// Areas for Narmada
const NARMADA_AREAS: AreaName[] = [
  "Rajpipla",
  "Dediapada",
  "Sagbara",
  "Tilakwada",
  "Nandod",
  "Kevadia",
  "Statue of Unity",
  "Sardar Sarovar Dam",
  "Forest Tribal Belt",
  "Narmada River Valley",
  "Eco-Tourism Belt",
  "Shoolpaneshwar Wildlife Sanctuary",
  "Hilly Tribal Settlements",
];

// Areas for Navsari
const NAVSARI_AREAS: AreaName[] = [
  "Navsari",
  "Vansda",
  "Chikhli",
  "Gandevi",
  "Jalalpore",
  "Bilimora",
  "Dandi Coastal Belt",
  "Pardi Influence Border",
  "Sugarcane Agricultural Belt",
  "Forest Vansda Region",
  "Coastal Fishing Villages",
  "Industrial Navsari Belt",
];

// Areas for Panchmahal
const PANCHMAHAL_AREAS: AreaName[] = [
  "Godhra",
  "Halol",
  "Kalol",
  "Jambughoda",
  "Ghoghamba",
  "Pavagadh Hill",
  "Champaner UNESCO",
  "Godhra Town",
  "Industrial Halol Belt",
  "Tribal Forest Region",
  "Mahi River Basin",
];

// Areas for Patan
const PATAN_AREAS: AreaName[] = [
  "Patan",
  "Sidhpur",
  "Chanasma",
  "Harij",
  "Radhanpur",
  "Sami",
  "Santalpur",
  "Rani ki Vav",
  "Modhera Sun Temple",
  "Sidhpur Heritage Town",
  "Dry Desert Belt",
  "Border Banaskantha Influence",
];

// Areas for Porbandar
const PORBANDAR_AREAS: AreaName[] = [
  "Porbandar",
  "Ranavav",
  "Kutiyana",
  "Madhavpur Beach",
  "Sudama Temple",
  "Fishing Harbour",
  "Barda Hills Forest",
  "Coastal Villages",
  "Ranavav Industrial Belt",
];

// Areas for Rajkot
const RAJKOT_AREAS: AreaName[] = [
  "Rajkot",
  "Gondal",
  "Jetpur",
  "Dhoraji",
  "Upleta",
  "Wankaner",
  "Kalawad Road",
  "150 Feet Ring Road",
  "Metoda GIDC",
  "Shapar-Veraval Industrial Belt",
  "Gondal Agricultural Belt",
  "Jetpur Textile Dyeing Hub",
  "Bedi Port",
  "Hilly Jasdan Belt",
];

// Areas for Sabarkantha
const SABARKANTHA_AREAS: AreaName[] = [
  "Himmatnagar",
  "Idar",
  "Khedbrahma",
  "Prantij",
  "Talod",
  "Vadali",
  "Aravalli Forest Belt",
  "Idar Hill Region",
  "Tribal Khedbrahma Belt",
  "Sabarmati River Basin",
  "Border Rajasthan Influence",
];

// Areas for Surat
const SURAT_AREAS: AreaName[] = [
  "Surat",
  "Bardoli",
  "Olpad",
  "Kamrej",
  "Palsana",
  "Mangrol",
  "Mandvi",
  "Surat City",
  "Varachha",
  "Katargam",
  "Adajan",
  "Udhna",
  "Sachin GIDC",
  "Hazira Port Industrial Zone",
  "Diamond Industry Hub",
  "Textile Market Ring Road",
  "Dumas Beach",
  "Industrial Corridor Sachin-Hazira",
  "Coastal Belt Villages",
  "Urban Expansion SMC Zones",
];

// Areas for Surendranagar
const SURENDRANAGAR_AREAS: AreaName[] = [
  "Surendranagar",
  "Wadhwan",
  "Dhrangadhra",
  "Limbdi",
  "Chotila",
  "Sayla",
  "Halvad",
  "Salt Desert Belt",
  "Little Rann of Kutch Edge",
  "Industrial Ceramic Belt",
  "Chotila Hill Pilgrimage",
  "Wadhwan Old City",
];

// Areas for Tapi
const TAPI_AREAS: AreaName[] = [
  "Vyara",
  "Songadh",
  "Valod",
  "Nizar",
  "Uchchhal",
  "Dolvan",
  "Saputara Forest Edge",
  "Tribal Belt",
  "Forest Hilly Region",
  "Maharashtra Border",
  "River Tapi Basin",
];

// Areas for Vadodara
const VADODARA_AREAS: AreaName[] = [
  "Vadodara",
  "Karjan",
  "Padra",
  "Savli",
  "Waghodia",
  "Dabhoi",
  "Alkapuri",
  "Manjalpur",
  "Fatehgunj",
  "Makarpura GIDC",
  "Halol Influence Belt",
  "Ajwa Lake",
  "Industrial Corridor",
  "Petrochemical Zone",
  "Railway Junction Hub",
  "Tarsali",
  "Waghodia Industrial Belt",
];

// Areas for Valsad
const VALSAD_AREAS: AreaName[] = [
  "Valsad",
  "Vapi",
  "Pardi",
  "Umargam",
  "Dharampur",
  "Kaprada",
  "Vapi GIDC",
  "Silvassa Border",
  "Coastal Umargam",
  "Tribal Kaprada Forest Belt",
  "Sugarcane Industrial Zone",
  "Coastal Fishing Villages",
  "NH-48 Industrial Corridor",
];

// Add more cities as needed (these can be added later)
// For now, only cities with areas defined are included
const GUJARAT_CITIES = {
  Ahmedabad: AHMEDABAD_AREAS,
  Surat: SURAT_AREAS,
  Gandhinagar: GANDHINAGAR_AREAS,
  Vadodara: VADODARA_AREAS,
  Rajkot: RAJKOT_AREAS,
  Jamnagar: JAMNAGAR_AREAS,
  Bhavnagar: BHAVNAGAR_AREAS,
  Anand: ANAND_AREAS,
  Kheda: KHEDA_AREAS,
  Mehsana: MEHSANA_AREAS,
  Surendranagar: SURENDRANAGAR_AREAS,
  Dahod: DAHOD_AREAS,
  Alirajpur: ALIRAJPUR_AREAS,
  Valsad: VALSAD_AREAS,
  Navsari: NAVSARI_AREAS,
  Bharuch: BHARUCH_AREAS,
  Nadiad: NADIAD_AREAS,
  Amreli: AMRELI_AREAS,
  Aravalli: ARAVALLI_AREAS,
  Banaskantha: BANASKANTHA_AREAS,
  Botad: BOTAD_AREAS,
  "Chhota Udaipur": CHHOTA_UIDAPUR_AREAS,
  Dang: DANG_AREAS,
  "Devbhoomi Dwarka": DEVBHOOMI_DWARKA_AREAS,
  "Gir Somnath": GIR_SOMNATH_AREAS,
  Junagadh: JUNAGADH_AREAS,
  Kutch: KUTCH_AREAS,
  Mahisagar: MAHISAGAR_AREAS,
  Morbi: MORBI_AREAS,
  Narmada: NARMADA_AREAS,
  Panchmahal: PANCHMAHAL_AREAS,
  Patan: PATAN_AREAS,
  Porbandar: PORBANDAR_AREAS,
  Sabarkantha: SABARKANTHA_AREAS,
  Tapi: TAPI_AREAS,
};

// Use a type assertion to allow partial city coverage for all states
export const LOCATION_DATA: Record<StateName, Partial<Record<CityName, AreaName[]>>> = {} as Record<StateName, Partial<Record<CityName, AreaName[]>>>;

// Initialize Gujarat cities
LOCATION_DATA.Gujarat = GUJARAT_CITIES;

// Helper functions for type-safe access
export const getCitiesForState = (state: string): CityName[] => {
  if (state in LOCATION_DATA && LOCATION_DATA[state as StateName]) {
    return Object.keys(LOCATION_DATA[state as StateName]) as CityName[];
  }
  return [];
};

export const getAreasForCity = (state: string, city: string): AreaName[] => {
  if (state in LOCATION_DATA && LOCATION_DATA[state as StateName] && city in LOCATION_DATA[state as StateName]) {
    const areas = LOCATION_DATA[state as StateName][city as CityName];
    return areas || [];
  }
  return [];
};

export const getAllStates = (): StateName[] => [...INDIAN_STATES];

export const getAllCities = (): CityName[] => {
  const cities = new Set<CityName>();
  Object.values(LOCATION_DATA).forEach((cityAreas) => {
    if (cityAreas) {
      Object.keys(cityAreas).forEach((city) => cities.add(city as CityName));
    }
  });
  return [...cities];
};

export const getAllAreas = (): AreaName[] => {
  const areas = new Set<AreaName>();
  Object.values(LOCATION_DATA).forEach((cityAreas) => {
    if (cityAreas) {
      Object.values(cityAreas).forEach((areaList) => {
        areaList.forEach((area) => areas.add(area));
      });
    }
  });
  return [...areas];
};
